ModelDistiller:
  distill_mode: false
  train_with_professor: false
anneal_factor: 2
ast:
  Corpus: SEMEVAL16-TR:SEMEVAL16-ES:SEMEVAL16-NL:SEMEVAL16-EN:SEMEVAL16-RU
  tag_dictionary: resources/taggers/ast_tags.pkl
cs:
  Corpus: CALCS-AR:CALCS-EN
  tag_dictionary: resources/taggers/cs_tags.pkl
embeddings:
  BertEmbeddings:
    bert_model_or_path: bert-base-multilingual-cased
    layers: '-1'
    pooling_operation: mean
  FlairEmbeddings-1:
    model: nl-forward
  FlairEmbeddings-2:
    model: nl-backward
  WordEmbeddings:
    embeddings: nl
interpolation: 0.5
is_teacher_list: true
model:
  FastSequenceTagger:
    biaf_attention: false
    crf_attention: false
    hidden_size: 256
    sentence_loss: true
    token_level_attention: false
    use_crf: true
model_name: multi_bert_origflair_300epoch_2000batch_1lr_256hidden_nl_monolingual_crf_sentloss_10patience_baseline_fast_nodev_ner11
ner:
  Corpus: CONLL_03_DUTCH
  professors:
    config/single-de-ner.yaml: CONLL_03_GERMAN
    config/single-en-ner.yaml: CONLL_03
    config/single-es-ner.yaml: CONLL_03_SPANISH
    config/single-nl-ner.yaml: CONLL_03_DUTCH
  tag_dictionary: resources/taggers/ner_tags.pkl
  teachers:
    ? config_gen/multi_bert_origflair_300epoch_2000batch_1lr_256hidden_de_monolingual_crf_sentloss_10patience_baseline_nodev_ner0.yaml
    : CONLL_03_GERMAN
    ? config_gen/multi_bert_origflair_300epoch_2000batch_1lr_256hidden_en_monolingual_crf_sentloss_10patience_baseline_nodev_ner0.yaml
    : CONLL_03
    ? config_gen/multi_bert_origflair_300epoch_2000batch_1lr_256hidden_es_monolingual_crf_sentloss_10patience_baseline_nodev_ner1.yaml
    : CONLL_03_SPANISH
    ? config_gen/multi_bert_origflair_300epoch_2000batch_1lr_256hidden_nl_monolingual_crf_sentloss_10patience_baseline_nodev_ner0.yaml
    : CONLL_03_DUTCH
np:
  Corpus: CONLL_03:CONLL_03_GERMAN:CONLL_03_VIETNAMESE
  professors:
    ? config_gen/multi_bert_origflair_300epoch_2000batch_1lr_400hidden_de_monolingual_crf_sentloss_10patience_baseline_fast_nodev_np6.yaml
    : CONLL_03_GERMAN
    ? config_gen/multi_bert_origflair_300epoch_2000batch_1lr_400hidden_vi_monolingual_crf_sentloss_10patience_baseline_fast_nodev_np6.yaml
    : CONLL_03_VIETNAMESE
    ? config_gen/multi_bert_origflair_300epoch_2000batch_1lr_600hidden_en_monolingual_crf_sentloss_10patience_baseline_fast_nodev_np7.yaml
    : CONLL_03
  tag_dictionary: resources/taggers/np_tags.pkl
  teachers:
    ? config_gen/multi_bert_origflair_300epoch_2000batch_1lr_400hidden_de_monolingual_crf_sentloss_10patience_baseline_fast_nodev_np6.yaml
    : CONLL_03_GERMAN
    ? config_gen/multi_bert_origflair_300epoch_2000batch_1lr_400hidden_vi_monolingual_crf_sentloss_10patience_baseline_fast_nodev_np6.yaml
    : CONLL_03_VIETNAMESE
    ? config_gen/multi_bert_origflair_300epoch_2000batch_1lr_600hidden_en_monolingual_crf_sentloss_10patience_baseline_fast_nodev_np7.yaml
    : CONLL_03
target_dir: resources/taggers/
targets: ner
teacher_annealing: false
train:
  learning_rate: 0.1
  max_epochs: 300
  mini_batch_size: 2000
  monitor_test: false
  patience: 10
  professor_interpolation: 0.5
  save_final_model: false
  train_with_dev: false
  true_reshuffle: false
upos:
  Corpus: UD_GERMAN:UD_ENGLISH:UD_FRENCH:UD_ITALIAN:UD_DUTCH:UD_SPANISH:UD_PORTUGUESE:UD_JAPANESE
  UD_GERMAN:
    train_config: config/
  professors:
    ? config_gen/multi_bert_origflair_300epoch_2000batch_1lr_400hidden_de_monolingual_crf_sentloss_10patience_baseline_fast_nodev_upos1.yaml
    : UD_GERMAN
    ? config_gen/multi_bert_origflair_300epoch_2000batch_1lr_400hidden_en_monolingual_crf_sentloss_10patience_baseline_fast_nodev_upos0.yaml
    : UD_ENGLISH
    ? config_gen/multi_bert_origflair_300epoch_2000batch_1lr_400hidden_es_monolingual_crf_sentloss_10patience_baseline_fast_nodev_upos0.yaml
    : UD_SPANISH
    ? config_gen/multi_bert_origflair_300epoch_2000batch_1lr_400hidden_fr_monolingual_crf_sentloss_10patience_baseline_fast_nodev_upos1.yaml
    : UD_FRENCH
    ? config_gen/multi_bert_origflair_300epoch_2000batch_1lr_400hidden_it_monolingual_crf_sentloss_10patience_baseline_fast_nodev_upos1.yaml
    : UD_ITALIAN
    ? config_gen/multi_bert_origflair_300epoch_2000batch_1lr_400hidden_ja_monolingual_crf_sentloss_10patience_baseline_fast_nodev_upos1.yaml
    : UD_JAPANESE
    ? config_gen/multi_bert_origflair_300epoch_2000batch_1lr_400hidden_nl_monolingual_crf_sentloss_10patience_baseline_fast_nodev_upos1.yaml
    : UD_DUTCH
    ? config_gen/multi_bert_origflair_300epoch_2000batch_1lr_400hidden_pt_monolingual_crf_sentloss_10patience_baseline_fast_nodev_upos1.yaml
    : UD_PORTUGUESE
  tag_dictionary: resources/taggers/pos_tags.pkl
  teachers:
    ? config_gen/multi_bert_origflair_300epoch_2000batch_1lr_400hidden_de_monolingual_crf_sentloss_10patience_baseline_fast_nodev_upos1.yaml
    : UD_GERMAN
    ? config_gen/multi_bert_origflair_300epoch_2000batch_1lr_400hidden_en_monolingual_crf_sentloss_10patience_baseline_fast_nodev_upos0.yaml
    : UD_ENGLISH
    ? config_gen/multi_bert_origflair_300epoch_2000batch_1lr_400hidden_es_monolingual_crf_sentloss_10patience_baseline_fast_nodev_upos0.yaml
    : UD_SPANISH
    ? config_gen/multi_bert_origflair_300epoch_2000batch_1lr_400hidden_fr_monolingual_crf_sentloss_10patience_baseline_fast_nodev_upos1.yaml
    : UD_FRENCH
    ? config_gen/multi_bert_origflair_300epoch_2000batch_1lr_400hidden_it_monolingual_crf_sentloss_10patience_baseline_fast_nodev_upos1.yaml
    : UD_ITALIAN
    ? config_gen/multi_bert_origflair_300epoch_2000batch_1lr_400hidden_ja_monolingual_crf_sentloss_10patience_baseline_fast_nodev_upos1.yaml
    : UD_JAPANESE
    ? config_gen/multi_bert_origflair_300epoch_2000batch_1lr_400hidden_nl_monolingual_crf_sentloss_10patience_baseline_fast_nodev_upos1.yaml
    : UD_DUTCH
    ? config_gen/multi_bert_origflair_300epoch_2000batch_1lr_400hidden_pt_monolingual_crf_sentloss_10patience_baseline_fast_nodev_upos1.yaml
    : UD_PORTUGUESE
