ModelFinetuner:
  distill_mode: false
  train_with_professor: false
anneal_factor: 2
embeddings:
  BertEmbeddings:
    bert_model_or_path: bert-base-multilingual-cased
    fine_tune: true
    layers: '-1'
    pooling_operation: mean
    sentence_feat: false
interpolation: 0.5
is_teacher_list: true
model:
  FastSequenceTagger:
    crf_attention: false
    dropout: 0.0
    hidden_size: 256
    relearn_embeddings: true
    sentence_loss: true
    use_cnn: false
    use_crf: false
    use_rnn: false
model_name: multi_bert_10epoch_2000batch_0.00005lr_multilingual_nocrf_sentloss_baseline_fast_finetune_relearn_nodev_ner0
ner:
  Corpus: CONLL_03_DUTCH:CONLL_03_SPANISH:CONLL_03:CONLL_03_GERMAN
  professors:
    config_gen/multi_bert_flair_2000batch_1lr_de_monolingual_nocrf_sentloss_10patience_baseline_nodev_ner1.yaml: CONLL_03_GERMAN
    config_gen/multi_bert_flair_2000batch_1lr_en_monolingual_nocrf_sentloss_10patience_baseline_nodev_ner1.yaml: CONLL_03
    config_gen/multi_bert_flair_2000batch_1lr_es_monolingual_nocrf_sentloss_10patience_baseline_nodev_ner0.yaml: CONLL_03_SPANISH
    config_gen/multi_bert_flair_2000batch_1lr_nl_monolingual_nocrf_sentloss_10patience_baseline_nodev_ner1.yaml: CONLL_03_DUTCH
  tag_dictionary: resources/taggers/ner_tags.pkl
  teachers:
    config_gen/multi_bert_flair_2000batch_1lr_de_monolingual_nocrf_sentloss_10patience_baseline_nodev_ner1.yaml: CONLL_03_GERMAN
    config_gen/multi_bert_flair_2000batch_1lr_en_monolingual_nocrf_sentloss_10patience_baseline_nodev_ner1.yaml: CONLL_03
    config_gen/multi_bert_flair_2000batch_1lr_es_monolingual_nocrf_sentloss_10patience_baseline_nodev_ner0.yaml: CONLL_03_SPANISH
    config_gen/multi_bert_flair_2000batch_1lr_nl_monolingual_nocrf_sentloss_10patience_baseline_nodev_ner1.yaml: CONLL_03_DUTCH
target_dir: resources/taggers/
targets: ner
teacher_annealing: false
train:
  fine_tune_mode: true
  learning_rate: 5.0e-05
  max_epochs: 10
  mini_batch_size: 2000
  monitor_test: false
  professor_interpolation: 0.5
  save_final_model: false
  train_with_dev: false
  true_reshuffle: false
trainer: ModelFinetuner
upos:
  Corpus: UD_GERMAN:UD_ENGLISH:UD_FRENCH:UD_ITALIAN:UD_DUTCH:UD_SPANISH:UD_PORTUGUESE:UD_JAPANESE
  UD_GERMAN:
    train_config: config/
  professors:
    ? config_gen/multi_bert_origflair_300epoch_2000batch_1lr_400hidden_de_monolingual_nocrf_sentloss_10patience_baseline_fast_nodev_upos0.yaml
    : UD_GERMAN
    ? config_gen/multi_bert_origflair_300epoch_2000batch_1lr_400hidden_en_monolingual_nocrf_sentloss_10patience_baseline_fast_nodev_upos0.yaml
    : UD_ENGLISH
    ? config_gen/multi_bert_origflair_300epoch_2000batch_1lr_400hidden_es_monolingual_nocrf_sentloss_10patience_baseline_fast_nodev_upos0.yaml
    : UD_SPANISH
    ? config_gen/multi_bert_origflair_300epoch_2000batch_1lr_400hidden_fr_monolingual_nocrf_sentloss_10patience_baseline_fast_nodev_upos1.yaml
    : UD_FRENCH
    ? config_gen/multi_bert_origflair_300epoch_2000batch_1lr_400hidden_it_monolingual_nocrf_sentloss_10patience_baseline_fast_nodev_upos1.yaml
    : UD_ITALIAN
    ? config_gen/multi_bert_origflair_300epoch_2000batch_1lr_400hidden_ja_monolingual_nocrf_sentloss_10patience_baseline_fast_nodev_upos1.yaml
    : UD_JAPANESE
    ? config_gen/multi_bert_origflair_300epoch_2000batch_1lr_400hidden_nl_monolingual_nocrf_sentloss_10patience_baseline_fast_nodev_upos1.yaml
    : UD_DUTCH
    ? config_gen/multi_bert_origflair_300epoch_2000batch_1lr_400hidden_pt_monolingual_nocrf_sentloss_10patience_baseline_fast_nodev_upos0.yaml
    : UD_PORTUGUESE
  tag_dictionary: resources/taggers/pos_tags.pkl
  teachers:
    ? config_gen/multi_bert_origflair_300epoch_2000batch_1lr_400hidden_de_monolingual_nocrf_sentloss_10patience_baseline_fast_nodev_upos0.yaml
    : UD_GERMAN
    ? config_gen/multi_bert_origflair_300epoch_2000batch_1lr_400hidden_en_monolingual_nocrf_sentloss_10patience_baseline_fast_nodev_upos0.yaml
    : UD_ENGLISH
    ? config_gen/multi_bert_origflair_300epoch_2000batch_1lr_400hidden_es_monolingual_nocrf_sentloss_10patience_baseline_fast_nodev_upos0.yaml
    : UD_SPANISH
    ? config_gen/multi_bert_origflair_300epoch_2000batch_1lr_400hidden_fr_monolingual_nocrf_sentloss_10patience_baseline_fast_nodev_upos1.yaml
    : UD_FRENCH
    ? config_gen/multi_bert_origflair_300epoch_2000batch_1lr_400hidden_it_monolingual_nocrf_sentloss_10patience_baseline_fast_nodev_upos1.yaml
    : UD_ITALIAN
    ? config_gen/multi_bert_origflair_300epoch_2000batch_1lr_400hidden_ja_monolingual_nocrf_sentloss_10patience_baseline_fast_nodev_upos1.yaml
    : UD_JAPANESE
    ? config_gen/multi_bert_origflair_300epoch_2000batch_1lr_400hidden_nl_monolingual_nocrf_sentloss_10patience_baseline_fast_nodev_upos1.yaml
    : UD_DUTCH
    ? config_gen/multi_bert_origflair_300epoch_2000batch_1lr_400hidden_pt_monolingual_nocrf_sentloss_10patience_baseline_fast_nodev_upos0.yaml
    : UD_PORTUGUESE
