MFVI:
  hexa_rank: 150
  hexa_std: 1
  iterations: 3
  normalize_weight: true
  quad_rank: 150
  quad_std: 1
  tag_dim: 150
  use_hexalinear: false
  use_quadrilinear: false
  use_second_order: false
  use_third_order: false
  window_size: 1
ModelFinetuner:
  distill_mode: true
anneal_factor: 10.0
embeddings:
  BertEmbeddings:
    bert_model_or_path: bert-base-multilingual-cased
    fine_tune: true
    layers: '-1'
    pooling_operation: mean
    sentence_feat: false
interpolation: 0.5
is_teacher_list: true
model:
  FastSequenceTagger:
    crf_attention: false
    distill_crf: false
    distill_posterior: true
    dropout: 0.0
    hidden_size: 800
    relearn_embeddings: true
    sentence_loss: true
    temperature: 4.0
    use_cnn: false
    use_crf: true
    use_rnn: false
model_name: multi_bert_10epoch_10anneal_2000batch_0.00005lr_10000lrrate_5decay_800hidden_multilingual_crf_sentloss_distill_posterior_4temperature_fast_finetune_relearn_nodev_ner1
ner:
  Corpus: CONLL_03_DUTCH:CONLL_03_SPANISH:CONLL_03:CONLL_03_GERMAN
  tag_dictionary: resources/taggers/ner_tags.pkl
  teachers:
    ? config/multi_bert_origflair_300epoch_2000batch_1lr_256hidden_de_monolingual_crf_sentloss_10patience_baseline_fast_nodev_ner12.yaml
    : CONLL_03_GERMAN
    ? config/multi_bert_origflair_300epoch_2000batch_1lr_256hidden_en_monolingual_crf_sentloss_10patience_baseline_fast_nodev_ner11.yaml
    : CONLL_03
    ? config/multi_bert_origflair_300epoch_2000batch_1lr_256hidden_es_monolingual_crf_sentloss_10patience_baseline_fast_nodev_ner12.yaml
    : CONLL_03_SPANISH
    ? config/multi_bert_origflair_300epoch_2000batch_1lr_256hidden_nl_monolingual_crf_sentloss_10patience_baseline_fast_nodev_ner11.yaml
    : CONLL_03_DUTCH
target_dir: resources/taggers/
targets: ner
teacher_annealing: true
train:
  anneal_factor: 0.5
  fine_tune_mode: true
  learning_rate: 5.0e-05
  lr_rate: 10000
  max_epochs: 10
  mini_batch_size: 2000
  monitor_test: false
  save_final_model: false
  train_with_dev: false
  true_reshuffle: false
trainer: ModelFinetuner
